### PR TITLE
Update theano to 1.0.5 on linux64, ppc64le, osx64, win64, win32 platforms

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Bug Tracker: new open issues https://github.com/Theano/Theano/issues
Upstream license: https://github.com/Theano/Theano/blob/master/doc/LICENSE.txt
Changelog: https://github.com/Theano/Theano/blob/rel-1.0.5/HISTORY.txt
Upstream setup.py:  https://github.com/Theano/Theano/blob/rel-1.0.5/setup.py

The package theano is mentioned inside the packages:
theano-pymc |

Actions:
1. Add entry_points
2. Add missing packages: `pip`, `wheel`
3. Update test/imports
4. Fix license

Result:
- all-failed

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
An error on `s390x`:
```
conda.exceptions.ResolvePackageNotFound:
  - pygpu[version='>=0.7,<0.8.0a0']
```
Skip building on s390x

**Comment by skupr-anaconda** [comment]
Failed on all platforms with python 3.9

**Comment by skupr-anaconda** [comment]
After running:
`conda create -n test_env --dry-run python=3.9 cython pip setuptools wheel "numpy >=1.9.1" "scipy >=0.14" "six >=1.9.0" "pygpu >=0.7,<0.8"  -vvv 2>&1 | grep -e "-> 0"`

```
DEBUG conda.resolve:filter_group(635): pygpu: pruned from 10 -> 0
DEBUG conda.resolve:filter_group(635): pygpu: pruned from 10 -> 0
DEBUG conda.resolve:filter_group(635): pygpu: pruned from 10 -> 0
DEBUG conda.resolve:filter_group(635): pygpu: pruned from 10 -> 0
DEBUG conda.resolve:filter_group(635): pygpu: pruned from 13 -> 0
DEBUG conda.resolve:filter_group(635): pygpu: pruned from 13 -> 0
DEBUG conda.resolve:filter_group(635): pygpu: pruned from 13 -> 0
DEBUG conda.resolve:filter_group(635): pygpu: pruned from 13 -> 0

```
We should update` pygpu 0.7.6` and build it for py39

**Comment by skupr-anaconda** [comment]
Tests failed on `osx-64`

**Review by varlackc — COMMENTED** [review]
the `doc_url` and `home` url seem to be deprecated

**Comment by skupr-anaconda** [comment]
> the `doc_url` and `home` url seem to be deprecated

@varlackc I've updated home and doc urls

**Review by tobijk — APPROVED** [review]

**Pull request merged**
